### ISSUE TITLE
How to handle cron triggers in worker?

### ISSUE THREAD

**Issue by Boscop** [DylanRJohnston/leptos-cloudflare-example#1]
Thanks for this example repo :)

Cloudflare workers have the ability to not just be called based on incoming HTTP requests but also based on cron triggers:
https://developers.cloudflare.com/workers/configuration/cron-triggers/
https://developers.cloudflare.com/workers/examples/multiple-cron-triggers/

In JS this can easily be done by having an exported function named `scheduled` that gets called for cron triggers.

How can I handle cron triggers in a Rust/leptos based app, based on this template? :)

**Comment by DylanRJohnston** [comment]
Hey Boscop, I'd highly recommend reading through the documentation on https://rustwasm.github.io/wasm-bindgen/ as that will give you a good grasp of how to make your own interfaces between Rust and JS. It should look something like this.

https://rustwasm.github.io/wasm-bindgen/reference/attributes/on-rust-exports/js_name.html
```rs
#[wasm_bindgen(js_name = "scheduled")]
pub fn scheduled(event: JsValue, env: JsValue, ctx: JsValue) {
 // 
}
```

However you then have to do the work on coercing the JsValue types into the expected types. Luckily it looks like `worker-rs` actually has a macro to do this for you.

https://github.com/cloudflare/workers-rs/blob/main/worker-macros/src/event.rs#L114
```rs
#[event(scheduled)]
pub fn scheduled(event: worker::ScheduledEvent, env: worker::Env, ctx: worker::ScheduleContext) {
 // 
}
```

Hopefully that helps! Let me know if you have any other questions.

**Comment by Boscop** [comment]
Awesome, thanks :)
